// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class HouseholdMember implements SupadartClass<HouseholdMember> {
  final String householdId;
  final String userId;
  final String role;
  final DateTime joinedAt;

  const HouseholdMember({
    required this.householdId,
    required this.userId,
    required this.role,
    required this.joinedAt,
  });

  static String get table_name => 'household_members';
  static String get c_householdId => 'household_id';
  static String get c_userId => 'user_id';
  static String get c_role => 'role';
  static String get c_joinedAt => 'joined_at';

  static List<HouseholdMember> converter(List<Map<String, dynamic>> data) {
    return data.map(HouseholdMember.fromJson).toList();
  }

  static HouseholdMember converterSingle(Map<String, dynamic> data) {
    return HouseholdMember.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? householdId,
    String? userId,
    String? role,
    DateTime? joinedAt,
  }) {
    return {
      if (householdId != null) 'household_id': householdId,
      if (userId != null) 'user_id': userId,
      if (role != null) 'role': role,
      if (joinedAt != null) 'joined_at': joinedAt.toUtc().toIso8601String(),
    };
  }

  static Map<String, dynamic> insert({
    String? householdId,
    String? userId,
    String? role,
    DateTime? joinedAt,
  }) {
    return _generateMap(
      householdId: householdId,
      userId: userId,
      role: role,
      joinedAt: joinedAt,
    );
  }

  static Map<String, dynamic> update({
    String? householdId,
    String? userId,
    String? role,
    DateTime? joinedAt,
  }) {
    return _generateMap(
      householdId: householdId,
      userId: userId,
      role: role,
      joinedAt: joinedAt,
    );
  }

  factory HouseholdMember.fromJson(Map<String, dynamic> jsonn) {
    return HouseholdMember(
      householdId: jsonn['household_id'] != null
          ? jsonn['household_id'].toString()
          : '',
      userId: jsonn['user_id'] != null ? jsonn['user_id'].toString() : '',
      role: jsonn['role'] != null ? jsonn['role'].toString() : '',
      joinedAt: jsonn['joined_at'] != null
          ? DateTime.parse(jsonn['joined_at'].toString())
          : DateTime.fromMillisecondsSinceEpoch(0),
    );
  }

  static Object New({
    String? householdId,
    String? userId,
    String? role,
    DateTime? joinedAt,
  }) {
    return {
      if (householdId != null) 'household_id': householdId,
      if (userId != null) 'user_id': userId,
      if (role != null) 'role': role,
      if (joinedAt != null) 'joined_at': joinedAt,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      householdId: householdId,
      userId: userId,
      role: role,
      joinedAt: joinedAt,
    );
  }

  static const _unset = Object();
  HouseholdMember copyWith({
    Object? householdId = _unset,
    Object? userId = _unset,
    Object? role = _unset,
    Object? joinedAt = _unset,
  }) {
    return HouseholdMember(
      householdId: householdId == _unset
          ? this.householdId
          : householdId as String,
      userId: userId == _unset ? this.userId : userId as String,
      role: role == _unset ? this.role : role as String,
      joinedAt: joinedAt == _unset ? this.joinedAt : joinedAt as DateTime,
    );
  }
}
