// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class Household implements SupadartClass<Household> {
  final String id;
  final String name;
  final String inviteCode;
  final String? createdBy;
  final DateTime createdAt;

  const Household({
    required this.id,
    required this.name,
    required this.inviteCode,
    this.createdBy,
    required this.createdAt,
  });

  static String get table_name => 'households';
  static String get c_id => 'id';
  static String get c_name => 'name';
  static String get c_inviteCode => 'invite_code';
  static String get c_createdBy => 'created_by';
  static String get c_createdAt => 'created_at';

  static List<Household> converter(List<Map<String, dynamic>> data) {
    return data.map(Household.fromJson).toList();
  }

  static Household converterSingle(Map<String, dynamic> data) {
    return Household.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? id,
    String? name,
    String? inviteCode,
    String? createdBy,
    DateTime? createdAt,
  }) {
    return {
      'id': ?id,
      'name': ?name,
      'invite_code': ?inviteCode,
      'created_by': ?createdBy,
      if (createdAt != null) 'created_at': createdAt.toUtc().toIso8601String(),
    };
  }

  static Map<String, dynamic> insert({
    String? id,
    required String name,
    required String inviteCode,
    String? createdBy,
    DateTime? createdAt,
  }) {
    return _generateMap(
      id: id,
      name: name,
      inviteCode: inviteCode,
      createdBy: createdBy,
      createdAt: createdAt,
    );
  }

  static Map<String, dynamic> update({
    String? id,
    String? name,
    String? inviteCode,
    String? createdBy,
    DateTime? createdAt,
  }) {
    return _generateMap(
      id: id,
      name: name,
      inviteCode: inviteCode,
      createdBy: createdBy,
      createdAt: createdAt,
    );
  }

  factory Household.fromJson(Map<String, dynamic> jsonn) {
    return Household(
      id: jsonn['id'] != null ? jsonn['id'].toString() : '',
      name: jsonn['name'] != null ? jsonn['name'].toString() : '',
      inviteCode: jsonn['invite_code'] != null
          ? jsonn['invite_code'].toString()
          : '',
      createdBy: jsonn['created_by'] != null
          ? jsonn['created_by'].toString()
          : null,
      createdAt: jsonn['created_at'] != null
          ? DateTime.parse(jsonn['created_at'].toString())
          : DateTime.fromMillisecondsSinceEpoch(0),
    );
  }

  static Object New({
    String? id,
    String? name,
    String? inviteCode,
    String? createdBy,
    DateTime? createdAt,
  }) {
    return {
      'id': ?id,
      'name': ?name,
      'invite_code': ?inviteCode,
      'created_by': ?createdBy,
      'created_at': ?createdAt,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      id: id,
      name: name,
      inviteCode: inviteCode,
      createdBy: createdBy,
      createdAt: createdAt,
    );
  }

  static const _unset = Object();
  Household copyWith({
    Object? id = _unset,
    Object? name = _unset,
    Object? inviteCode = _unset,
    Object? createdBy = _unset,
    Object? createdAt = _unset,
  }) {
    return Household(
      id: id == _unset ? this.id : id as String,
      name: name == _unset ? this.name : name as String,
      inviteCode: inviteCode == _unset ? this.inviteCode : inviteCode as String,
      createdBy: createdBy == _unset ? this.createdBy : createdBy as String?,
      createdAt: createdAt == _unset ? this.createdAt : createdAt as DateTime,
    );
  }
}
