// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class Ingredient implements SupadartClass<Ingredient> {
  final String id;
  final String recipeId;
  final String name;
  final num? quantity;
  final String? unit;
  final String? category;
  final int position;

  const Ingredient({
    required this.id,
    required this.recipeId,
    required this.name,
    this.quantity,
    this.unit,
    this.category,
    required this.position,
  });

  static String get table_name => 'ingredients';
  static String get c_id => 'id';
  static String get c_recipeId => 'recipe_id';
  static String get c_name => 'name';
  static String get c_quantity => 'quantity';
  static String get c_unit => 'unit';
  static String get c_category => 'category';
  static String get c_position => 'position';

  static List<Ingredient> converter(List<Map<String, dynamic>> data) {
    return data.map(Ingredient.fromJson).toList();
  }

  static Ingredient converterSingle(Map<String, dynamic> data) {
    return Ingredient.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? id,
    String? recipeId,
    String? name,
    num? quantity,
    String? unit,
    String? category,
    int? position,
  }) {
    return {
      'id': ?id,
      'recipe_id': ?recipeId,
      'name': ?name,
      if (quantity != null) 'quantity': quantity.toString(),
      'unit': ?unit,
      'category': ?category,
      'position': ?position,
    };
  }

  static Map<String, dynamic> insert({
    String? id,
    required String recipeId,
    required String name,
    num? quantity,
    String? unit,
    String? category,
    int? position,
  }) {
    return _generateMap(
      id: id,
      recipeId: recipeId,
      name: name,
      quantity: quantity,
      unit: unit,
      category: category,
      position: position,
    );
  }

  static Map<String, dynamic> update({
    String? id,
    String? recipeId,
    String? name,
    num? quantity,
    String? unit,
    String? category,
    int? position,
  }) {
    return _generateMap(
      id: id,
      recipeId: recipeId,
      name: name,
      quantity: quantity,
      unit: unit,
      category: category,
      position: position,
    );
  }

  factory Ingredient.fromJson(Map<String, dynamic> jsonn) {
    return Ingredient(
      id: jsonn['id'] != null ? jsonn['id'].toString() : '',
      recipeId: jsonn['recipe_id'] != null ? jsonn['recipe_id'].toString() : '',
      name: jsonn['name'] != null ? jsonn['name'].toString() : '',
      quantity: jsonn['quantity'] != null
          ? num.parse(jsonn['quantity'].toString())
          : null,
      unit: jsonn['unit'] != null ? jsonn['unit'].toString() : null,
      category: jsonn['category'] != null ? jsonn['category'].toString() : null,
      position: jsonn['position'] != null
          ? int.parse(jsonn['position'].toString())
          : 0,
    );
  }

  static Object New({
    String? id,
    String? recipeId,
    String? name,
    num? quantity,
    String? unit,
    String? category,
    int? position,
  }) {
    return {
      'id': ?id,
      'recipe_id': ?recipeId,
      'name': ?name,
      'quantity': ?quantity,
      'unit': ?unit,
      'category': ?category,
      'position': ?position,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      id: id,
      recipeId: recipeId,
      name: name,
      quantity: quantity,
      unit: unit,
      category: category,
      position: position,
    );
  }

  static const _unset = Object();
  Ingredient copyWith({
    Object? id = _unset,
    Object? recipeId = _unset,
    Object? name = _unset,
    Object? quantity = _unset,
    Object? unit = _unset,
    Object? category = _unset,
    Object? position = _unset,
  }) {
    return Ingredient(
      id: id == _unset ? this.id : id as String,
      recipeId: recipeId == _unset ? this.recipeId : recipeId as String,
      name: name == _unset ? this.name : name as String,
      quantity: quantity == _unset ? this.quantity : quantity as num?,
      unit: unit == _unset ? this.unit : unit as String?,
      category: category == _unset ? this.category : category as String?,
      position: position == _unset ? this.position : position as int,
    );
  }
}
