// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class NutritionInfo implements SupadartClass<NutritionInfo> {
  final String id;
  final String recipeId;
  final num? calories;
  final num? protein;
  final num? carbohydrates;
  final num? fat;
  final num? fiber;

  const NutritionInfo({
    required this.id,
    required this.recipeId,
    this.calories,
    this.protein,
    this.carbohydrates,
    this.fat,
    this.fiber,
  });

  static String get table_name => 'nutrition_info';
  static String get c_id => 'id';
  static String get c_recipeId => 'recipe_id';
  static String get c_calories => 'calories';
  static String get c_protein => 'protein';
  static String get c_carbohydrates => 'carbohydrates';
  static String get c_fat => 'fat';
  static String get c_fiber => 'fiber';

  static List<NutritionInfo> converter(List<Map<String, dynamic>> data) {
    return data.map(NutritionInfo.fromJson).toList();
  }

  static NutritionInfo converterSingle(Map<String, dynamic> data) {
    return NutritionInfo.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? id,
    String? recipeId,
    num? calories,
    num? protein,
    num? carbohydrates,
    num? fat,
    num? fiber,
  }) {
    return {
      if (id != null) 'id': id,
      if (recipeId != null) 'recipe_id': recipeId,
      if (calories != null) 'calories': calories.toString(),
      if (protein != null) 'protein': protein.toString(),
      if (carbohydrates != null) 'carbohydrates': carbohydrates.toString(),
      if (fat != null) 'fat': fat.toString(),
      if (fiber != null) 'fiber': fiber.toString(),
    };
  }

  static Map<String, dynamic> insert({
    String? id,
    required String recipeId,
    num? calories,
    num? protein,
    num? carbohydrates,
    num? fat,
    num? fiber,
  }) {
    return _generateMap(
      id: id,
      recipeId: recipeId,
      calories: calories,
      protein: protein,
      carbohydrates: carbohydrates,
      fat: fat,
      fiber: fiber,
    );
  }

  static Map<String, dynamic> update({
    String? id,
    String? recipeId,
    num? calories,
    num? protein,
    num? carbohydrates,
    num? fat,
    num? fiber,
  }) {
    return _generateMap(
      id: id,
      recipeId: recipeId,
      calories: calories,
      protein: protein,
      carbohydrates: carbohydrates,
      fat: fat,
      fiber: fiber,
    );
  }

  factory NutritionInfo.fromJson(Map<String, dynamic> jsonn) {
    return NutritionInfo(
      id: jsonn['id'] != null ? jsonn['id'].toString() : '',
      recipeId: jsonn['recipe_id'] != null ? jsonn['recipe_id'].toString() : '',
      calories: jsonn['calories'] != null
          ? num.parse(jsonn['calories'].toString())
          : null,
      protein: jsonn['protein'] != null
          ? num.parse(jsonn['protein'].toString())
          : null,
      carbohydrates: jsonn['carbohydrates'] != null
          ? num.parse(jsonn['carbohydrates'].toString())
          : null,
      fat: jsonn['fat'] != null ? num.parse(jsonn['fat'].toString()) : null,
      fiber: jsonn['fiber'] != null
          ? num.parse(jsonn['fiber'].toString())
          : null,
    );
  }

  static Object New({
    String? id,
    String? recipeId,
    num? calories,
    num? protein,
    num? carbohydrates,
    num? fat,
    num? fiber,
  }) {
    return {
      if (id != null) 'id': id,
      if (recipeId != null) 'recipe_id': recipeId,
      if (calories != null) 'calories': calories,
      if (protein != null) 'protein': protein,
      if (carbohydrates != null) 'carbohydrates': carbohydrates,
      if (fat != null) 'fat': fat,
      if (fiber != null) 'fiber': fiber,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      id: id,
      recipeId: recipeId,
      calories: calories,
      protein: protein,
      carbohydrates: carbohydrates,
      fat: fat,
      fiber: fiber,
    );
  }

  static const _unset = Object();
  NutritionInfo copyWith({
    Object? id = _unset,
    Object? recipeId = _unset,
    Object? calories = _unset,
    Object? protein = _unset,
    Object? carbohydrates = _unset,
    Object? fat = _unset,
    Object? fiber = _unset,
  }) {
    return NutritionInfo(
      id: id == _unset ? this.id : id as String,
      recipeId: recipeId == _unset ? this.recipeId : recipeId as String,
      calories: calories == _unset ? this.calories : calories as num?,
      protein: protein == _unset ? this.protein : protein as num?,
      carbohydrates: carbohydrates == _unset
          ? this.carbohydrates
          : carbohydrates as num?,
      fat: fat == _unset ? this.fat : fat as num?,
      fiber: fiber == _unset ? this.fiber : fiber as num?,
    );
  }
}
