// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class PlanSlot implements SupadartClass<PlanSlot> {
  final String id;
  final String planId;
  final int dayOfWeek;
  final String mealType;
  final String? recipeId;
  final int servings;
  final int position;

  const PlanSlot({
    required this.id,
    required this.planId,
    required this.dayOfWeek,
    required this.mealType,
    this.recipeId,
    required this.servings,
    required this.position,
  });

  static String get table_name => 'plan_slots';
  static String get c_id => 'id';
  static String get c_planId => 'plan_id';
  static String get c_dayOfWeek => 'day_of_week';
  static String get c_mealType => 'meal_type';
  static String get c_recipeId => 'recipe_id';
  static String get c_servings => 'servings';
  static String get c_position => 'position';

  static List<PlanSlot> converter(List<Map<String, dynamic>> data) {
    return data.map(PlanSlot.fromJson).toList();
  }

  static PlanSlot converterSingle(Map<String, dynamic> data) {
    return PlanSlot.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? id,
    String? planId,
    int? dayOfWeek,
    String? mealType,
    String? recipeId,
    int? servings,
    int? position,
  }) {
    return {
      'id': ?id,
      'plan_id': ?planId,
      'day_of_week': ?dayOfWeek,
      'meal_type': ?mealType,
      'recipe_id': ?recipeId,
      'servings': ?servings,
      'position': ?position,
    };
  }

  static Map<String, dynamic> insert({
    String? id,
    required String planId,
    required int dayOfWeek,
    required String mealType,
    String? recipeId,
    int? servings,
    int? position,
  }) {
    return _generateMap(
      id: id,
      planId: planId,
      dayOfWeek: dayOfWeek,
      mealType: mealType,
      recipeId: recipeId,
      servings: servings,
      position: position,
    );
  }

  static Map<String, dynamic> update({
    String? id,
    String? planId,
    int? dayOfWeek,
    String? mealType,
    String? recipeId,
    int? servings,
    int? position,
  }) {
    return _generateMap(
      id: id,
      planId: planId,
      dayOfWeek: dayOfWeek,
      mealType: mealType,
      recipeId: recipeId,
      servings: servings,
      position: position,
    );
  }

  factory PlanSlot.fromJson(Map<String, dynamic> jsonn) {
    return PlanSlot(
      id: jsonn['id'] != null ? jsonn['id'].toString() : '',
      planId: jsonn['plan_id'] != null ? jsonn['plan_id'].toString() : '',
      dayOfWeek: jsonn['day_of_week'] != null
          ? int.parse(jsonn['day_of_week'].toString())
          : 0,
      mealType: jsonn['meal_type'] != null ? jsonn['meal_type'].toString() : '',
      recipeId: jsonn['recipe_id'] != null
          ? jsonn['recipe_id'].toString()
          : null,
      servings: jsonn['servings'] != null
          ? int.parse(jsonn['servings'].toString())
          : 0,
      position: jsonn['position'] != null
          ? int.parse(jsonn['position'].toString())
          : 0,
    );
  }

  static Object New({
    String? id,
    String? planId,
    int? dayOfWeek,
    String? mealType,
    String? recipeId,
    int? servings,
    int? position,
  }) {
    return {
      'id': ?id,
      'plan_id': ?planId,
      'day_of_week': ?dayOfWeek,
      'meal_type': ?mealType,
      'recipe_id': ?recipeId,
      'servings': ?servings,
      'position': ?position,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      id: id,
      planId: planId,
      dayOfWeek: dayOfWeek,
      mealType: mealType,
      recipeId: recipeId,
      servings: servings,
      position: position,
    );
  }

  static const _unset = Object();
  PlanSlot copyWith({
    Object? id = _unset,
    Object? planId = _unset,
    Object? dayOfWeek = _unset,
    Object? mealType = _unset,
    Object? recipeId = _unset,
    Object? servings = _unset,
    Object? position = _unset,
  }) {
    return PlanSlot(
      id: id == _unset ? this.id : id as String,
      planId: planId == _unset ? this.planId : planId as String,
      dayOfWeek: dayOfWeek == _unset ? this.dayOfWeek : dayOfWeek as int,
      mealType: mealType == _unset ? this.mealType : mealType as String,
      recipeId: recipeId == _unset ? this.recipeId : recipeId as String?,
      servings: servings == _unset ? this.servings : servings as int,
      position: position == _unset ? this.position : position as int,
    );
  }
}
