// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class Profile implements SupadartClass<Profile> {
  final String id;
  final String username;
  final String? avatarUrl;
  final DateTime createdAt;

  const Profile({
    required this.id,
    required this.username,
    this.avatarUrl,
    required this.createdAt,
  });

  static String get table_name => 'profiles';
  static String get c_id => 'id';
  static String get c_username => 'username';
  static String get c_avatarUrl => 'avatar_url';
  static String get c_createdAt => 'created_at';

  static List<Profile> converter(List<Map<String, dynamic>> data) {
    return data.map(Profile.fromJson).toList();
  }

  static Profile converterSingle(Map<String, dynamic> data) {
    return Profile.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? id,
    String? username,
    String? avatarUrl,
    DateTime? createdAt,
  }) {
    return {
      if (id != null) 'id': id,
      if (username != null) 'username': username,
      if (avatarUrl != null) 'avatar_url': avatarUrl,
      if (createdAt != null) 'created_at': createdAt.toUtc().toIso8601String(),
    };
  }

  static Map<String, dynamic> insert({
    String? id,
    required String username,
    String? avatarUrl,
    DateTime? createdAt,
  }) {
    return _generateMap(
      id: id,
      username: username,
      avatarUrl: avatarUrl,
      createdAt: createdAt,
    );
  }

  static Map<String, dynamic> update({
    String? id,
    String? username,
    String? avatarUrl,
    DateTime? createdAt,
  }) {
    return _generateMap(
      id: id,
      username: username,
      avatarUrl: avatarUrl,
      createdAt: createdAt,
    );
  }

  factory Profile.fromJson(Map<String, dynamic> jsonn) {
    return Profile(
      id: jsonn['id'] != null ? jsonn['id'].toString() : '',
      username: jsonn['username'] != null ? jsonn['username'].toString() : '',
      avatarUrl: jsonn['avatar_url'] != null
          ? jsonn['avatar_url'].toString()
          : null,
      createdAt: jsonn['created_at'] != null
          ? DateTime.parse(jsonn['created_at'].toString())
          : DateTime.fromMillisecondsSinceEpoch(0),
    );
  }

  static Object New({
    String? id,
    String? username,
    String? avatarUrl,
    DateTime? createdAt,
  }) {
    return {
      if (id != null) 'id': id,
      if (username != null) 'username': username,
      if (avatarUrl != null) 'avatar_url': avatarUrl,
      if (createdAt != null) 'created_at': createdAt,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      id: id,
      username: username,
      avatarUrl: avatarUrl,
      createdAt: createdAt,
    );
  }

  static const _unset = Object();
  Profile copyWith({
    Object? id = _unset,
    Object? username = _unset,
    Object? avatarUrl = _unset,
    Object? createdAt = _unset,
  }) {
    return Profile(
      id: id == _unset ? this.id : id as String,
      username: username == _unset ? this.username : username as String,
      avatarUrl: avatarUrl == _unset ? this.avatarUrl : avatarUrl as String?,
      createdAt: createdAt == _unset ? this.createdAt : createdAt as DateTime,
    );
  }
}
