// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class Recipe implements SupadartClass<Recipe> {
  final String id;
  final String userId;
  final String title;
  final String? photoUrl;
  final int servings;
  final int? prepTime;
  final int? cookTime;
  final List<String> tags;
  final bool isPublic;
  final DateTime createdAt;
  final DateTime updatedAt;

  const Recipe({
    required this.id,
    required this.userId,
    required this.title,
    this.photoUrl,
    required this.servings,
    this.prepTime,
    this.cookTime,
    required this.tags,
    required this.isPublic,
    required this.createdAt,
    required this.updatedAt,
  });

  static String get table_name => 'recipes';
  static String get c_id => 'id';
  static String get c_userId => 'user_id';
  static String get c_title => 'title';
  static String get c_photoUrl => 'photo_url';
  static String get c_servings => 'servings';
  static String get c_prepTime => 'prep_time';
  static String get c_cookTime => 'cook_time';
  static String get c_tags => 'tags';
  static String get c_isPublic => 'is_public';
  static String get c_createdAt => 'created_at';
  static String get c_updatedAt => 'updated_at';

  static List<Recipe> converter(List<Map<String, dynamic>> data) {
    return data.map(Recipe.fromJson).toList();
  }

  static Recipe converterSingle(Map<String, dynamic> data) {
    return Recipe.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? id,
    String? userId,
    String? title,
    String? photoUrl,
    int? servings,
    int? prepTime,
    int? cookTime,
    List<String>? tags,
    bool? isPublic,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return {
      if (id != null) 'id': id,
      if (userId != null) 'user_id': userId,
      if (title != null) 'title': title,
      if (photoUrl != null) 'photo_url': photoUrl,
      if (servings != null) 'servings': servings,
      if (prepTime != null) 'prep_time': prepTime,
      if (cookTime != null) 'cook_time': cookTime,
      if (tags != null) 'tags': tags.map((e) => e).toList(),
      if (isPublic != null) 'is_public': isPublic,
      if (createdAt != null) 'created_at': createdAt.toUtc().toIso8601String(),
      if (updatedAt != null) 'updated_at': updatedAt.toUtc().toIso8601String(),
    };
  }

  static Map<String, dynamic> insert({
    String? id,
    required String userId,
    required String title,
    String? photoUrl,
    int? servings,
    int? prepTime,
    int? cookTime,
    required List<String> tags,
    bool? isPublic,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return _generateMap(
      id: id,
      userId: userId,
      title: title,
      photoUrl: photoUrl,
      servings: servings,
      prepTime: prepTime,
      cookTime: cookTime,
      tags: tags,
      isPublic: isPublic,
      createdAt: createdAt,
      updatedAt: updatedAt,
    );
  }

  static Map<String, dynamic> update({
    String? id,
    String? userId,
    String? title,
    String? photoUrl,
    int? servings,
    int? prepTime,
    int? cookTime,
    List<String>? tags,
    bool? isPublic,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return _generateMap(
      id: id,
      userId: userId,
      title: title,
      photoUrl: photoUrl,
      servings: servings,
      prepTime: prepTime,
      cookTime: cookTime,
      tags: tags,
      isPublic: isPublic,
      createdAt: createdAt,
      updatedAt: updatedAt,
    );
  }

  factory Recipe.fromJson(Map<String, dynamic> jsonn) {
    return Recipe(
      id: jsonn['id'] != null ? jsonn['id'].toString() : '',
      userId: jsonn['user_id'] != null ? jsonn['user_id'].toString() : '',
      title: jsonn['title'] != null ? jsonn['title'].toString() : '',
      photoUrl: jsonn['photo_url'] != null
          ? jsonn['photo_url'].toString()
          : null,
      servings: jsonn['servings'] != null
          ? int.parse(jsonn['servings'].toString())
          : 0,
      prepTime: jsonn['prep_time'] != null
          ? int.parse(jsonn['prep_time'].toString())
          : null,
      cookTime: jsonn['cook_time'] != null
          ? int.parse(jsonn['cook_time'].toString())
          : null,
      tags: jsonn['tags'] != null
          ? (jsonn['tags'] as List<dynamic>).map((v) => v.toString()).toList()
          : <String>[],
      isPublic: jsonn['is_public'] != null ? jsonn['is_public'] as bool : false,
      createdAt: jsonn['created_at'] != null
          ? DateTime.parse(jsonn['created_at'].toString())
          : DateTime.fromMillisecondsSinceEpoch(0),
      updatedAt: jsonn['updated_at'] != null
          ? DateTime.parse(jsonn['updated_at'].toString())
          : DateTime.fromMillisecondsSinceEpoch(0),
    );
  }

  static Object New({
    String? id,
    String? userId,
    String? title,
    String? photoUrl,
    int? servings,
    int? prepTime,
    int? cookTime,
    List<String>? tags,
    bool? isPublic,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return {
      if (id != null) 'id': id,
      if (userId != null) 'user_id': userId,
      if (title != null) 'title': title,
      if (photoUrl != null) 'photo_url': photoUrl,
      if (servings != null) 'servings': servings,
      if (prepTime != null) 'prep_time': prepTime,
      if (cookTime != null) 'cook_time': cookTime,
      if (tags != null) 'tags': tags,
      if (isPublic != null) 'is_public': isPublic,
      if (createdAt != null) 'created_at': createdAt,
      if (updatedAt != null) 'updated_at': updatedAt,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      id: id,
      userId: userId,
      title: title,
      photoUrl: photoUrl,
      servings: servings,
      prepTime: prepTime,
      cookTime: cookTime,
      tags: tags,
      isPublic: isPublic,
      createdAt: createdAt,
      updatedAt: updatedAt,
    );
  }

  static const _unset = Object();
  Recipe copyWith({
    Object? id = _unset,
    Object? userId = _unset,
    Object? title = _unset,
    Object? photoUrl = _unset,
    Object? servings = _unset,
    Object? prepTime = _unset,
    Object? cookTime = _unset,
    Object? tags = _unset,
    Object? isPublic = _unset,
    Object? createdAt = _unset,
    Object? updatedAt = _unset,
  }) {
    return Recipe(
      id: id == _unset ? this.id : id as String,
      userId: userId == _unset ? this.userId : userId as String,
      title: title == _unset ? this.title : title as String,
      photoUrl: photoUrl == _unset ? this.photoUrl : photoUrl as String?,
      servings: servings == _unset ? this.servings : servings as int,
      prepTime: prepTime == _unset ? this.prepTime : prepTime as int?,
      cookTime: cookTime == _unset ? this.cookTime : cookTime as int?,
      tags: tags == _unset ? this.tags : tags as List<String>,
      isPublic: isPublic == _unset ? this.isPublic : isPublic as bool,
      createdAt: createdAt == _unset ? this.createdAt : createdAt as DateTime,
      updatedAt: updatedAt == _unset ? this.updatedAt : updatedAt as DateTime,
    );
  }
}
