// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class ShoppingItem implements SupadartClass<ShoppingItem> {
  final String id;
  final String shoppingListId;
  final String name;
  final num? quantity;
  final String? unit;
  final String? category;
  final bool isChecked;
  final bool isManual;
  final String? planSlotId;
  final String? ingredientId;
  final DateTime createdAt;

  const ShoppingItem({
    required this.id,
    required this.shoppingListId,
    required this.name,
    this.quantity,
    this.unit,
    this.category,
    required this.isChecked,
    required this.isManual,
    this.planSlotId,
    this.ingredientId,
    required this.createdAt,
  });

  static String get table_name => 'shopping_items';
  static String get c_id => 'id';
  static String get c_shoppingListId => 'shopping_list_id';
  static String get c_name => 'name';
  static String get c_quantity => 'quantity';
  static String get c_unit => 'unit';
  static String get c_category => 'category';
  static String get c_isChecked => 'is_checked';
  static String get c_isManual => 'is_manual';
  static String get c_planSlotId => 'plan_slot_id';
  static String get c_ingredientId => 'ingredient_id';
  static String get c_createdAt => 'created_at';

  static List<ShoppingItem> converter(List<Map<String, dynamic>> data) {
    return data.map(ShoppingItem.fromJson).toList();
  }

  static ShoppingItem converterSingle(Map<String, dynamic> data) {
    return ShoppingItem.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? id,
    String? shoppingListId,
    String? name,
    num? quantity,
    String? unit,
    String? category,
    bool? isChecked,
    bool? isManual,
    String? planSlotId,
    String? ingredientId,
    DateTime? createdAt,
  }) {
    return {
      if (id != null) 'id': id,
      if (shoppingListId != null) 'shopping_list_id': shoppingListId,
      if (name != null) 'name': name,
      if (quantity != null) 'quantity': quantity.toString(),
      if (unit != null) 'unit': unit,
      if (category != null) 'category': category,
      if (isChecked != null) 'is_checked': isChecked,
      if (isManual != null) 'is_manual': isManual,
      if (planSlotId != null) 'plan_slot_id': planSlotId,
      if (ingredientId != null) 'ingredient_id': ingredientId,
      if (createdAt != null) 'created_at': createdAt.toUtc().toIso8601String(),
    };
  }

  static Map<String, dynamic> insert({
    String? id,
    required String shoppingListId,
    required String name,
    num? quantity,
    String? unit,
    String? category,
    bool? isChecked,
    bool? isManual,
    String? planSlotId,
    String? ingredientId,
    DateTime? createdAt,
  }) {
    return _generateMap(
      id: id,
      shoppingListId: shoppingListId,
      name: name,
      quantity: quantity,
      unit: unit,
      category: category,
      isChecked: isChecked,
      isManual: isManual,
      planSlotId: planSlotId,
      ingredientId: ingredientId,
      createdAt: createdAt,
    );
  }

  static Map<String, dynamic> update({
    String? id,
    String? shoppingListId,
    String? name,
    num? quantity,
    String? unit,
    String? category,
    bool? isChecked,
    bool? isManual,
    String? planSlotId,
    String? ingredientId,
    DateTime? createdAt,
  }) {
    return _generateMap(
      id: id,
      shoppingListId: shoppingListId,
      name: name,
      quantity: quantity,
      unit: unit,
      category: category,
      isChecked: isChecked,
      isManual: isManual,
      planSlotId: planSlotId,
      ingredientId: ingredientId,
      createdAt: createdAt,
    );
  }

  factory ShoppingItem.fromJson(Map<String, dynamic> jsonn) {
    return ShoppingItem(
      id: jsonn['id'] != null ? jsonn['id'].toString() : '',
      shoppingListId: jsonn['shopping_list_id'] != null
          ? jsonn['shopping_list_id'].toString()
          : '',
      name: jsonn['name'] != null ? jsonn['name'].toString() : '',
      quantity: jsonn['quantity'] != null
          ? num.parse(jsonn['quantity'].toString())
          : null,
      unit: jsonn['unit'] != null ? jsonn['unit'].toString() : null,
      category: jsonn['category'] != null ? jsonn['category'].toString() : null,
      isChecked: jsonn['is_checked'] != null
          ? jsonn['is_checked'] as bool
          : false,
      isManual: jsonn['is_manual'] != null ? jsonn['is_manual'] as bool : false,
      planSlotId: jsonn['plan_slot_id'] != null
          ? jsonn['plan_slot_id'].toString()
          : null,
      ingredientId: jsonn['ingredient_id'] != null
          ? jsonn['ingredient_id'].toString()
          : null,
      createdAt: jsonn['created_at'] != null
          ? DateTime.parse(jsonn['created_at'].toString())
          : DateTime.fromMillisecondsSinceEpoch(0),
    );
  }

  static Object New({
    String? id,
    String? shoppingListId,
    String? name,
    num? quantity,
    String? unit,
    String? category,
    bool? isChecked,
    bool? isManual,
    String? planSlotId,
    String? ingredientId,
    DateTime? createdAt,
  }) {
    return {
      if (id != null) 'id': id,
      if (shoppingListId != null) 'shopping_list_id': shoppingListId,
      if (name != null) 'name': name,
      if (quantity != null) 'quantity': quantity,
      if (unit != null) 'unit': unit,
      if (category != null) 'category': category,
      if (isChecked != null) 'is_checked': isChecked,
      if (isManual != null) 'is_manual': isManual,
      if (planSlotId != null) 'plan_slot_id': planSlotId,
      if (ingredientId != null) 'ingredient_id': ingredientId,
      if (createdAt != null) 'created_at': createdAt,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      id: id,
      shoppingListId: shoppingListId,
      name: name,
      quantity: quantity,
      unit: unit,
      category: category,
      isChecked: isChecked,
      isManual: isManual,
      planSlotId: planSlotId,
      ingredientId: ingredientId,
      createdAt: createdAt,
    );
  }

  static const _unset = Object();
  ShoppingItem copyWith({
    Object? id = _unset,
    Object? shoppingListId = _unset,
    Object? name = _unset,
    Object? quantity = _unset,
    Object? unit = _unset,
    Object? category = _unset,
    Object? isChecked = _unset,
    Object? isManual = _unset,
    Object? planSlotId = _unset,
    Object? ingredientId = _unset,
    Object? createdAt = _unset,
  }) {
    return ShoppingItem(
      id: id == _unset ? this.id : id as String,
      shoppingListId: shoppingListId == _unset
          ? this.shoppingListId
          : shoppingListId as String,
      name: name == _unset ? this.name : name as String,
      quantity: quantity == _unset ? this.quantity : quantity as num?,
      unit: unit == _unset ? this.unit : unit as String?,
      category: category == _unset ? this.category : category as String?,
      isChecked: isChecked == _unset ? this.isChecked : isChecked as bool,
      isManual: isManual == _unset ? this.isManual : isManual as bool,
      planSlotId: planSlotId == _unset
          ? this.planSlotId
          : planSlotId as String?,
      ingredientId: ingredientId == _unset
          ? this.ingredientId
          : ingredientId as String?,
      createdAt: createdAt == _unset ? this.createdAt : createdAt as DateTime,
    );
  }
}
