// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class ShoppingList implements SupadartClass<ShoppingList> {
  final String id;
  final String? householdId;
  final String? userId;
  final DateTime createdAt;

  const ShoppingList({
    required this.id,
    this.householdId,
    this.userId,
    required this.createdAt,
  });

  static String get table_name => 'shopping_lists';
  static String get c_id => 'id';
  static String get c_householdId => 'household_id';
  static String get c_userId => 'user_id';
  static String get c_createdAt => 'created_at';

  static List<ShoppingList> converter(List<Map<String, dynamic>> data) {
    return data.map(ShoppingList.fromJson).toList();
  }

  static ShoppingList converterSingle(Map<String, dynamic> data) {
    return ShoppingList.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? id,
    String? householdId,
    String? userId,
    DateTime? createdAt,
  }) {
    return {
      if (id != null) 'id': id,
      if (householdId != null) 'household_id': householdId,
      if (userId != null) 'user_id': userId,
      if (createdAt != null) 'created_at': createdAt.toUtc().toIso8601String(),
    };
  }

  static Map<String, dynamic> insert({
    String? id,
    String? householdId,
    String? userId,
    DateTime? createdAt,
  }) {
    return _generateMap(
      id: id,
      householdId: householdId,
      userId: userId,
      createdAt: createdAt,
    );
  }

  static Map<String, dynamic> update({
    String? id,
    String? householdId,
    String? userId,
    DateTime? createdAt,
  }) {
    return _generateMap(
      id: id,
      householdId: householdId,
      userId: userId,
      createdAt: createdAt,
    );
  }

  factory ShoppingList.fromJson(Map<String, dynamic> jsonn) {
    return ShoppingList(
      id: jsonn['id'] != null ? jsonn['id'].toString() : '',
      householdId: jsonn['household_id'] != null
          ? jsonn['household_id'].toString()
          : null,
      userId: jsonn['user_id'] != null ? jsonn['user_id'].toString() : null,
      createdAt: jsonn['created_at'] != null
          ? DateTime.parse(jsonn['created_at'].toString())
          : DateTime.fromMillisecondsSinceEpoch(0),
    );
  }

  static Object New({
    String? id,
    String? householdId,
    String? userId,
    DateTime? createdAt,
  }) {
    return {
      if (id != null) 'id': id,
      if (householdId != null) 'household_id': householdId,
      if (userId != null) 'user_id': userId,
      if (createdAt != null) 'created_at': createdAt,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      id: id,
      householdId: householdId,
      userId: userId,
      createdAt: createdAt,
    );
  }

  static const _unset = Object();
  ShoppingList copyWith({
    Object? id = _unset,
    Object? householdId = _unset,
    Object? userId = _unset,
    Object? createdAt = _unset,
  }) {
    return ShoppingList(
      id: id == _unset ? this.id : id as String,
      householdId: householdId == _unset
          ? this.householdId
          : householdId as String?,
      userId: userId == _unset ? this.userId : userId as String?,
      createdAt: createdAt == _unset ? this.createdAt : createdAt as DateTime,
    );
  }
}
