// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison,prefer_null_aware_operators


// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the SupaDart configuration.


// SDK
import 'package:supabase_flutter/supabase_flutter.dart';


// No geobase needed
// No Intl package needed
// No Dart Convert needed
// No JSONB Model imports needed
// Supadart Class
abstract class SupadartClass<T> {
  static Map<String, dynamic> insert(Map<String, dynamic> data) {
    throw UnimplementedError();
  }

  static Map<String, dynamic> update(Map<String, dynamic> data) {
    throw UnimplementedError();
  }

  factory SupadartClass.fromJson(Map<String, dynamic> json) {
    throw UnimplementedError();
  }

  static converter(List<Map<String, dynamic>> data) {
    throw UnimplementedError();
  }

  static converterSingle(Map<String, dynamic> data) {
    throw UnimplementedError();
  }
    
}



// Supabase Client Extension
extension SupadartClient on SupabaseClient {
SupabaseQueryBuilder get plan_slots => from('plan_slots');
SupabaseQueryBuilder get households => from('households');
SupabaseQueryBuilder get profiles => from('profiles');
SupabaseQueryBuilder get weekly_plans => from('weekly_plans');
SupabaseQueryBuilder get nutrition_info => from('nutrition_info');
SupabaseQueryBuilder get recipe_steps => from('recipe_steps');
SupabaseQueryBuilder get shopping_items => from('shopping_items');
SupabaseQueryBuilder get household_members => from('household_members');
SupabaseQueryBuilder get recipes => from('recipes');
SupabaseQueryBuilder get shopping_lists => from('shopping_lists');
SupabaseQueryBuilder get ingredients => from('ingredients');
}



// Supabase Storage Client Extension
extension SupadartStorageClient on SupabaseStorageClient {
StorageFileApi get recipe-photos => from('recipe-photos');
}



// Enums

// Utils
