// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison, prefer_null_aware_operators

// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the SupaDart configuration.

import 'package:supabase_flutter/supabase_flutter.dart';

abstract class SupadartClass<T> {
  static Map<String, dynamic> insert(Map<String, dynamic> data) {
    throw UnimplementedError();
  }

  static Map<String, dynamic> update(Map<String, dynamic> data) {
    throw UnimplementedError();
  }

  factory SupadartClass.fromJson(Map<String, dynamic> json) {
    throw UnimplementedError();
  }
}

extension SupadartClient on SupabaseClient {
  SupabaseQueryBuilder get plan_slots => from('plan_slots');
  SupabaseQueryBuilder get households => from('households');
  SupabaseQueryBuilder get profiles => from('profiles');
  SupabaseQueryBuilder get weekly_plans => from('weekly_plans');
  SupabaseQueryBuilder get nutrition_info => from('nutrition_info');
  SupabaseQueryBuilder get recipe_steps => from('recipe_steps');
  SupabaseQueryBuilder get shopping_items => from('shopping_items');
  SupabaseQueryBuilder get household_members => from('household_members');
  SupabaseQueryBuilder get recipes => from('recipes');
  SupabaseQueryBuilder get shopping_lists => from('shopping_lists');
  SupabaseQueryBuilder get ingredients => from('ingredients');
}

extension SupadartStorageClient on SupabaseStorageClient {
  StorageFileApi get recipe_photos => from('recipe-photos');
}
