// File generated by FlutterFire CLI — synced to core/firebase for app imports.
// Re-run `flutterfire configure` in meal_planner/ after adding Firebase apps.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

abstract final class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web — '
        'run `flutterfire configure` with web support.',
      );
    }
    return switch (defaultTargetPlatform) {
      TargetPlatform.android => android,
      TargetPlatform.iOS => ios,
      TargetPlatform.macOS => macos,
      _ => throw UnsupportedError(
          'Firebase is not configured for $defaultTargetPlatform.',
        ),
    };
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCueuJ-ZiGjmpZQxav0IKQ32-zSJGIRF9Q',
    appId: '1:271085053235:android:ad6d8573806095624c0a46',
    messagingSenderId: '271085053235',
    projectId: 'mealplanner-a818e',
    storageBucket: 'mealplanner-a818e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLwYQiidLtLEhoYjLQApUSygXMGJ8IpJo',
    appId: '1:271085053235:ios:76b46bb2e84fcb2b4c0a46',
    messagingSenderId: '271085053235',
    projectId: 'mealplanner-a818e',
    storageBucket: 'mealplanner-a818e.firebasestorage.app',
    iosBundleId: 'com.japegomez.mealPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLwYQiidLtLEhoYjLQApUSygXMGJ8IpJo',
    appId: '1:271085053235:ios:76b46bb2e84fcb2b4c0a46',
    messagingSenderId: '271085053235',
    projectId: 'mealplanner-a818e',
    storageBucket: 'mealplanner-a818e.firebasestorage.app',
    iosBundleId: 'com.japegomez.mealPlanner',
  );

  static bool get isConfigured =>
      android.apiKey.isNotEmpty &&
      android.projectId.isNotEmpty &&
      !android.apiKey.startsWith('REPLACE');
}
