name: Flutter CI

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

jobs:
  flutter-ci:
    name: flutter-ci
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: meal_planner

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze --fatal-infos lib test

      - name: Run unit tests
        run: flutter test
